/**
 * @hyzyn/dsh-tty — tmux 会话持久化（0.10.0）。
 *
 * 目标：给「需要活得比宿主久」的工作（dev server、build、训练任务）一个显式
 * 逃生门。默认安全模型不变 —— 会话仍随宿主生死（内核级 PTY 清理）；持久标签
 * 只是把会话状态委托给 tmux server（专用 socket `dsh-tty`，与用户自己的 tmux
 * 完全隔离）托管：浏览器断线、保活窗口超时、甚至宿主重启后，重开标签用同一
 * 持久名 `new-session -A` 即可接回原现场（正在跑的程序、pane 状态原样恢复）。
 *
 * 职责：
 *   1. probeTmux()       —— 探测 tmux 可用性与版本（≥3.3 才支持 DCS
 *                           allow-passthrough，agent 命令粒度工具依赖它），
 *                           30s TTL 缓存；不可用时 spawn 走普通会话 + 灰字提示；
 *   2. ensureTmuxAssets  —— 在稳定目录（pluginRuntimeDir()）生成 tmux.conf 与
 *                           内层启动器 inner.sh（write-if-changed 原子覆盖）；
 *                           tmux server 只在首次启动读 conf，路径必须稳定；
 *   3. buildTmuxSpawnPlan—— 组装 `-c` 包装层：TERM/COLORTERM 注入 + exec tmux
 *                           客户端（`-A` attach-or-create；cwd 由 node-pty 的
 *                           spawn cwd 继承，tmux 新 session 以此为 pane cwd）；
 *   4. killTmuxSession   —— kill 帧的 tmux 侧收尾：kill-session 让 pane 随之
 *                           结束（会话真正关闭，而不是 detach 留活口）。
 *
 * 残留会话边界：宿主被硬杀/浏览器丢失标签规格时，tmux server 上的会话会留存
 * （这正是恢复能力的前提），直到机器重启或手动 `tmux -L dsh-tty kill-server`；
 * 专用 socket 让这些残留对用户的 tmux 世界完全不可见（README 已知限制）。
 */
import { execFile } from 'node:child_process'
import type { ShellSpawnPlan } from './shell-integration.js'
import { buildTmuxInnerLauncher, pluginRuntimeDir, shSingleQuote } from './shell-integration.js'
import { chmodSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** 专用 tmux socket 名：与用户自己的 tmux server 完全隔离。 */
export const TMUX_SOCKET = 'dsh-tty'

/** 探测结果：available = tmux 存在；passthrough = 版本 ≥3.3（DCS 信封可转发）。 */
export interface TmuxProbe {
  available: boolean
  passthrough: boolean
}

let probeCache: { at: number; value: TmuxProbe } | null = null
const PROBE_TTL_MS = 30_000

/** 探测 tmux 可用性与版本（30s TTL；execFile 3s 超时）。 */
export async function probeTmux(): Promise<TmuxProbe> {
  if (probeCache !== null && Date.now() - probeCache.at < PROBE_TTL_MS) return probeCache.value
  const value = await new Promise<TmuxProbe>((resolve) => {
    execFile('tmux', ['-V'], { timeout: 3000 }, (error, stdout) => {
      if (error !== null && error !== undefined) {
        resolve({ available: false, passthrough: false })
        return
      }
      const match = /tmux\s+(\d+)\.(\d+)/.exec(String(stdout))
      if (match === null) {
        resolve({ available: false, passthrough: false })
        return
      }
      const major = Number(match[1])
      const minor = Number(match[2])
      resolve({ available: true, passthrough: major > 3 || (major === 3 && minor >= 3) })
    })
  })
  probeCache = { at: Date.now(), value }
  return value
}

/** spawn 帧里的持久名清洗：合法字符集加 `dsh-` 前缀；不合法退回 sid 派生名。 */
export function sanitizePersistName(raw: unknown, sid: string): string {
  const name = typeof raw === 'string' ? raw.trim() : ''
  if (/^[A-Za-z0-9_-]{1,48}$/.test(name)) return `dsh-${name}`
  return `dsh-${sid.replace(/[^A-Za-z0-9_-]/g, '')}`
}

/** write-if-changed + rename（与 shell-integration 桩同策略；目录自动创建）。 */
function writeIfChanged(file: string, content: string): void {
  try {
    if (readFileSync(file, 'utf8') === content) return
  } catch {
    /* 不存在：继续写入 */
  }
  mkdirSync(dirname(file), { recursive: true })
  const tmp = `${file}.${process.pid}.tmp`
  writeFileSync(tmp, content)
  renameSync(tmp, file)
}

function dirname(path: string): string {
  const index = path.lastIndexOf('/')
  return index > 0 ? path.slice(0, index) : '/'
}

/** 组装 tmux.conf：状态栏关（防重绘污染 capture）、真色透传、内层启动器。 */
function buildTmuxConf(passthrough: boolean, runtimeDir: string): string {
  const lines = [
    '# generated by dsh-tty（会话持久化）— 手改会在下次生成时被覆盖；',
    '# tmux server 仅首次启动读取本文件，改完需 `tmux -L ' + TMUX_SOCKET + ' kill-server` 或重启宿主生效',
    'set -g default-terminal "screen-256color"',
    'set -ga terminal-overrides ",*:RGB"',
    'set -g status off',
    'set -g history-limit 20000',
    `set -g default-command ${shSingleQuote(join(runtimeDir, 'inner.sh'))}`,
  ]
  if (passthrough) lines.push('set -g allow-passthrough on')
  return lines.join('\n') + '\n'
}

/**
 * 生成/刷新 tmux 运行资产（tmux.conf + inner.sh）：每个持久 spawn 前调用，
 * 内容随当前配置（shell / shellIntegration / passthrough）write-if-changed。
 * conf 只在 tmux server 首启时被读，后续 spawn 的重写不生效 —— 但 inner.sh
 * 内容每次开 pane 都会重新执行，配置热改对持久标签的新 pane 仍然生效。
 */
export function ensureTmuxAssets(options: { shell: string; colorTerm: string; shellIntegration: boolean; passthrough: boolean }): void {
  const runtimeDir = pluginRuntimeDir()
  writeIfChanged(join(runtimeDir, 'tmux.conf'), buildTmuxConf(options.passthrough, runtimeDir))
  const inner = join(runtimeDir, 'inner.sh')
  writeIfChanged(inner, buildTmuxInnerLauncher(options.shell, options.colorTerm, options.shellIntegration))
  try {
    chmodSync(inner, 0o755)
  } catch {
    /* chmod 失败由 exec 阶段自然报错 */
  }
}

/**
 * 持久本地会话的 `-c` 包装层：TERM/COLORTERM 注入（与普通会话同机制）后
 * `exec tmux -A` attach-or-create。持久名已过 sanitizePersistName（安全字符集），
 * 单引号包裹防注入；cwd 不进命令行 —— tmux 客户端继承 node-pty spawn 的 cwd，
 * 新 session 的 pane 以此为工作目录。
 */
export function buildTmuxSpawnPlan(options: { shell: string; term: string; colorTerm: string; tmuxName: string }): ShellSpawnPlan {
  const runtimeDir = pluginRuntimeDir()
  const pre = `export TERM=${shSingleQuote(options.term)}; export COLORTERM=${shSingleQuote(options.colorTerm)};`
  const exec = [
    'exec tmux',
    '-L', TMUX_SOCKET,
    '-f', shSingleQuote(join(runtimeDir, 'tmux.conf')),
    'new-session -A -s', shSingleQuote(options.tmuxName),
  ].join(' ')
  return { argv: [options.shell, '-c', `${pre} ${exec}`], env: {} }
}

/** kill 帧的 tmux 侧收尾：kill-session（不存在/已死同样 resolve，错误吞掉）。 */
export function killTmuxSession(tmuxName: string): Promise<void> {
  return new Promise((resolve) => {
    execFile('tmux', ['-L', TMUX_SOCKET, 'kill-session', '-t', tmuxName], { timeout: 4000 }, () => resolve())
  })
}

/**
 * attach 重画：tmux 背书会话重连时不回放宿主环形缓冲（tmux 的整屏重画会把
 * 同样内容再画一遍 → 重影 + 幽灵滚动条），改为让 tmux 强制重画客户端一次。
 * refresh-client 的 -t 收的是 client（tty）名，先经 list-clients -t <会话>
 * 拿到该会话当前 attached 的客户端再刷新；任何失败静默吞掉（极端情况下
 * 用户敲一次键 tmux 也会重画）。
 */
export function refreshTmuxClient(tmuxName: string): Promise<void> {
  return new Promise((resolve) => {
    execFile('tmux', ['-L', TMUX_SOCKET, 'list-clients', '-t', tmuxName, '-F', '#{client_name}'], { timeout: 4000 }, (error, stdout) => {
      const client = String(stdout).trim().split('\n')[0] ?? ''
      if ((error !== null && error !== undefined) || client === '') {
        resolve()
        return
      }
      execFile('tmux', ['-L', TMUX_SOCKET, 'refresh-client', '-t', client], { timeout: 4000 }, () => resolve())
    })
  })
}
