// 本文件由 scripts/sync-routes.mjs 自动生成，请勿手改。
// 数据源: https://jackyst0.github.io/awesome-rsshub-routes/
// 上游: JackyST0/awesome-rsshub-routes 的 feeds.opml
// 生成时间: 2026-08-17T05:23:01.665Z（98 条订阅源 / 12 个分类）

export interface RouteRecord {
  name: string
  category: string
  url: string
}

export const ROUTES: RouteRecord[] = [
  { name: "OpenAI 博客", category: "🤖 AI 专题", url: "https://openai.com/news/rss.xml" },
  { name: "Google DeepMind", category: "🤖 AI 专题", url: "https://deepmind.google/blog/rss.xml" },
  { name: "Google AI Blog", category: "🤖 AI 专题", url: "https://blog.google/technology/ai/rss/" },
  { name: "arXiv AI", category: "🤖 AI 专题", url: "https://rss.arxiv.org/rss/cs.AI" },
  { name: "arXiv 机器学习", category: "🤖 AI 专题", url: "https://rss.arxiv.org/rss/cs.LG" },
  { name: "arXiv NLP", category: "🤖 AI 专题", url: "https://rss.arxiv.org/rss/cs.CL" },
  { name: "arXiv 计算机视觉", category: "🤖 AI 专题", url: "https://rss.arxiv.org/rss/cs.CV" },
  { name: "Hacker News AI", category: "🤖 AI 专题", url: "https://hnrss.org/newest?q=AI" },
  { name: "Hacker News LLM", category: "🤖 AI 专题", url: "https://hnrss.org/newest?q=LLM" },
  { name: "Hacker News OpenClaw", category: "🤖 AI 专题", url: "https://hnrss.org/newest?q=OpenClaw" },
  { name: "Google Research Blog", category: "🤖 AI 专题", url: "https://research.google/blog/rss/" },
  { name: "Hugging Face 博客", category: "🤖 AI 专题", url: "https://huggingface.co/blog/feed.xml" },
  { name: "Stability AI", category: "🤖 AI 专题", url: "https://stability.ai/news?format=rss" },
  { name: "OpenClaw Releases", category: "🤖 AI 专题", url: "https://github.com/openclaw/openclaw/releases.atom" },
  { name: "OpenClaw Commits", category: "🤖 AI 专题", url: "https://github.com/openclaw/openclaw/commits/main.atom" },
  { name: "机器之心", category: "🤖 AI 专题", url: "https://www.jiqizhixin.com/rss" },
  { name: "Simon Willison", category: "🤖 AI 专题", url: "https://simonwillison.net/atom/everything/" },
  { name: "OpenAI Codex Releases", category: "🤖 AI 专题", url: "https://github.com/openai/codex/releases.atom" },
  { name: "Claude Code Releases", category: "🤖 AI 专题", url: "https://github.com/anthropics/claude-code/releases.atom" },
  { name: "Gemini CLI Releases", category: "🤖 AI 专题", url: "https://github.com/google-gemini/gemini-cli/releases.atom" },
  { name: "MCP Specification Releases", category: "🤖 AI 专题", url: "https://github.com/modelcontextprotocol/specification/releases.atom" },
  { name: "MCP Servers Releases", category: "🤖 AI 专题", url: "https://github.com/modelcontextprotocol/servers/releases.atom" },
  { name: "LinuxDo 最新话题", category: "💻 技术社区", url: "https://linux.do/latest.rss" },
  { name: "LinuxDo 热门话题", category: "💻 技术社区", url: "https://linux.do/top.rss" },
  { name: "V2EX 最热", category: "💻 技术社区", url: "https://www.v2ex.com/feed/tab/hot.xml" },
  { name: "V2EX 技术", category: "💻 技术社区", url: "https://www.v2ex.com/feed/tab/tech.xml" },
  { name: "NodeSeek 最新话题", category: "💻 技术社区", url: "https://rss.nodeseek.com/" },
  { name: "奶昔论坛最新话题", category: "💻 技术社区", url: "https://forum.naixi.net/forum.php?mod=rss" },
  { name: "Hacker News 首页", category: "💻 技术社区", url: "https://hnrss.org/frontpage" },
  { name: "Hacker News 最佳", category: "💻 技术社区", url: "https://hnrss.org/best" },
  { name: "Hacker News Ask", category: "💻 技术社区", url: "https://hnrss.org/ask" },
  { name: "Hacker News Show", category: "💻 技术社区", url: "https://hnrss.org/show" },
  { name: "少数派", category: "💻 技术社区", url: "https://sspai.com/feed" },
  { name: "阮一峰的网络日志", category: "💻 技术社区", url: "https://www.ruanyifeng.com/blog/atom.xml" },
  { name: "IT之家", category: "📰 新闻资讯", url: "https://www.ithome.com/rss/" },
  { name: "TechCrunch", category: "🌐 科技媒体", url: "https://techcrunch.com/feed/" },
  { name: "The Verge", category: "🌐 科技媒体", url: "https://www.theverge.com/rss/index.xml" },
  { name: "Wired", category: "🌐 科技媒体", url: "https://www.wired.com/feed/rss" },
  { name: "Ars Technica", category: "🌐 科技媒体", url: "https://feeds.arstechnica.com/arstechnica/index" },
  { name: "MIT Technology Review", category: "🌐 科技媒体", url: "https://www.technologyreview.com/feed/" },
  { name: "Krebs on Security", category: "🛡️ 安全资讯", url: "https://krebsonsecurity.com/feed/" },
  { name: "The Hacker News", category: "🛡️ 安全资讯", url: "https://feeds.feedburner.com/TheHackersNews" },
  { name: "Schneier on Security", category: "🛡️ 安全资讯", url: "https://www.schneier.com/feed/" },
  { name: "CISA News", category: "🛡️ 安全资讯", url: "https://www.cisa.gov/news.xml" },
  { name: "Google Security Blog", category: "🛡️ 安全资讯", url: "https://security.googleblog.com/atom.xml" },
  { name: "FreeBuf", category: "🛡️ 安全资讯", url: "https://www.freebuf.com/feed" },
  { name: "安全客", category: "🛡️ 安全资讯", url: "https://api.anquanke.com/data/v1/rss" },
  { name: "Smashing Magazine", category: "🎨 前端 & 设计", url: "https://www.smashingmagazine.com/feed/" },
  { name: "A List Apart", category: "🎨 前端 & 设计", url: "https://alistapart.com/main/feed/" },
  { name: "Codrops", category: "🎨 前端 & 设计", url: "https://tympanus.net/codrops/feed/" },
  { name: "CSS-Tricks", category: "🎨 前端 & 设计", url: "https://css-tricks.com/feed/" },
  { name: "Astro Blog", category: "🎨 前端 & 设计", url: "https://astro.build/rss.xml" },
  { name: "Svelte Blog", category: "🎨 前端 & 设计", url: "https://svelte.dev/blog/rss.xml" },
  { name: "Next.js Blog", category: "🎨 前端 & 设计", url: "https://nextjs.org/feed.xml" },
  { name: "Nuxt Blog", category: "🎨 前端 & 设计", url: "https://nuxt.com/blog/rss.xml" },
  { name: "Tailwind CSS Blog", category: "🎨 前端 & 设计", url: "https://tailwindcss.com/feeds/feed.xml" },
  { name: "Dev.to", category: "🎨 前端 & 设计", url: "https://dev.to/feed" },
  { name: "Chrome Developer Blog", category: "🎨 前端 & 设计", url: "https://developer.chrome.com/blog/feed.xml" },
  { name: "Dribbble Popular", category: "🎨 前端 & 设计", url: "https://dribbble.com/shots/popular.rss" },
  { name: "Product Hunt", category: "🎨 前端 & 设计", url: "https://www.producthunt.com/feed" },
  { name: "React Blog", category: "📦 编程语言官方博客", url: "https://react.dev/rss.xml" },
  { name: "Vue Blog", category: "📦 编程语言官方博客", url: "https://blog.vuejs.org/feed.rss" },
  { name: "Rust Blog", category: "📦 编程语言官方博客", url: "https://blog.rust-lang.org/feed.xml" },
  { name: "Go Blog", category: "📦 编程语言官方博客", url: "https://go.dev/blog/feed.atom" },
  { name: "Python Blog", category: "📦 编程语言官方博客", url: "https://blog.python.org/feeds/posts/default" },
  { name: "Node.js Blog", category: "📦 编程语言官方博客", url: "https://nodejs.org/en/feed/blog.xml" },
  { name: "Deno Blog", category: "📦 编程语言官方博客", url: "https://deno.com/blog/feed.xml" },
  { name: "TypeScript Blog", category: "📦 编程语言官方博客", url: "https://devblogs.microsoft.com/typescript/feed/" },
  { name: "Swift Blog", category: "📦 编程语言官方博客", url: "https://www.swift.org/atom.xml" },
  { name: "Kotlin Blog", category: "📦 编程语言官方博客", url: "https://blog.jetbrains.com/kotlin/feed/" },
  { name: "GitHub Blog", category: "🏢 大厂技术博客", url: "https://github.blog/feed/" },
  { name: "GitHub Changelog", category: "🏢 大厂技术博客", url: "https://github.blog/changelog/feed/" },
  { name: "GitHub Copilot Changelog", category: "🏢 大厂技术博客", url: "https://github.blog/changelog/label/copilot/feed/" },
  { name: "Netflix Tech Blog", category: "🏢 大厂技术博客", url: "https://netflixtechblog.com/feed" },
  { name: "AWS Blog", category: "🏢 大厂技术博客", url: "https://aws.amazon.com/blogs/aws/feed/" },
  { name: "Cloudflare Blog", category: "🏢 大厂技术博客", url: "https://blog.cloudflare.com/rss/" },
  { name: "Google Developers", category: "🏢 大厂技术博客", url: "https://developers.googleblog.com/feeds/posts/default/" },
  { name: "Mozilla Hacks", category: "🏢 大厂技术博客", url: "https://hacks.mozilla.org/feed/" },
  { name: "Vercel Blog", category: "🏢 大厂技术博客", url: "https://vercel.com/atom" },
  { name: "Supabase Blog", category: "🏢 大厂技术博客", url: "https://supabase.com/rss.xml" },
  { name: "Stripe Blog", category: "🏢 大厂技术博客", url: "https://stripe.com/blog/feed.rss" },
  { name: "Spotify Engineering", category: "🏢 大厂技术博客", url: "https://engineering.atspotify.com/feed/" },
  { name: "Meta Engineering", category: "🏢 大厂技术博客", url: "https://engineering.fb.com/feed/" },
  { name: "JavaScript Weekly", category: "📮 技术周刊", url: "https://javascriptweekly.com/rss/" },
  { name: "This Week in Rust", category: "📮 技术周刊", url: "https://this-week-in-rust.org/atom.xml" },
  { name: "Golang Weekly", category: "📮 技术周刊", url: "https://golangweekly.com/rss/" },
  { name: "ByteByteGo", category: "📮 技术周刊", url: "https://blog.bytebytego.com/feed" },
  { name: "uv Releases", category: "🧰 开发工具版本追踪", url: "https://github.com/astral-sh/uv/releases.atom" },
  { name: "Zed Releases", category: "🧰 开发工具版本追踪", url: "https://github.com/zed-industries/zed/releases.atom" },
  { name: "Bun Releases", category: "🧰 开发工具版本追踪", url: "https://github.com/oven-sh/bun/releases.atom" },
  { name: "Biome Releases", category: "🧰 开发工具版本追踪", url: "https://github.com/biomejs/biome/releases.atom" },
  { name: "LangChain Releases", category: "🧰 开发工具版本追踪", url: "https://github.com/langchain-ai/langchain/releases.atom" },
  { name: "Nature", category: "📚 学术论文", url: "https://www.nature.com/nature.rss" },
  { name: "RSSHub Releases", category: "🔧 RSS 工具更新", url: "https://github.com/DIYgod/RSSHub/releases.atom" },
  { name: "RSSHub Radar Releases", category: "🔧 RSS 工具更新", url: "https://github.com/DIYgod/RSSHub-Radar/releases.atom" },
  { name: "Fluent Reader Releases", category: "🔧 RSS 工具更新", url: "https://github.com/yang991178/fluent-reader/releases.atom" },
  { name: "NetNewsWire Releases", category: "🔧 RSS 工具更新", url: "https://github.com/Ranchero-Software/NetNewsWire/releases.atom" },
  { name: "FreshRSS Releases", category: "🔧 RSS 工具更新", url: "https://github.com/FreshRSS/FreshRSS/releases.atom" },
]
