#!/usr/bin/env node
/**
 * 生成 @hyzyn/dsh-all 聚合清单：
 *   packages/all/cordis.patch.yml —— 自身行 + 全部插件行
 *   packages/all/package.json dependencies —— 全部插件 workspace:*
 * 扫描规则：packages 下各子目录的 package.json 含 dsh.bundle.patch、且包名不是 @hyzyn/dsh-all。
 * 每行的 id 与包名从插件自己的 cordis.patch.yml 提取。
 * 用法：pnpm aggregate（仓库根目录）
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const packagesDir = join(root, 'packages')
const ALL_NAME = '@hyzyn/dsh-all'

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'))
}

/** 从插件自己的 cordis.patch.yml 提取 insert 行（id + 包名）。 */
function extractRows(yaml) {
  const rows = []
  const lines = yaml.split(/\r?\n/)
  for (let i = 0; i < lines.length; i++) {
    const idMatch = /^\s*-\s+id:\s*(\S+)\s*$/.exec(lines[i])
    if (!idMatch) continue
    let pkg = null
    for (let j = i + 1; j < Math.min(lines.length, i + 4); j++) {
      const nameMatch = /^\s*name:\s*'([^']+)'\s*$/.exec(lines[j])
      if (nameMatch) {
        pkg = nameMatch[1]
        break
      }
    }
    if (pkg) rows.push({ id: idMatch[1], name: pkg })
  }
  return rows
}

const plugins = []
for (const dir of readdirSync(packagesDir).sort()) {
  if (!/^[a-z0-9-]+$/.test(dir)) continue
  const pkgPath = join(packagesDir, dir, 'package.json')
  let pkg
  try {
    pkg = readJson(pkgPath)
  } catch {
    continue
  }
  if (pkg.name === ALL_NAME) continue
  const patchRel = pkg.dsh?.bundle?.patch
  if (!patchRel) continue
  let rows
  try {
    rows = extractRows(readFileSync(join(packagesDir, dir, patchRel), 'utf8'))
  } catch {
    continue
  }
  if (rows.length === 0) {
    console.warn(`[aggregate] 跳过 ${pkg.name}：cordis.patch.yml 中没有可提取的行`)
    continue
  }
  plugins.push({ dir, name: pkg.name, rows, version: pkg.version })
}

// 1) 重写 packages/all/cordis.patch.yml
const out = ['# AUTO-GENERATED by scripts/aggregate.mjs — do not edit', '# 重新生成：pnpm aggregate', '']
out.push('# from self')
out.push('- insert:')
out.push('    - id: all')
out.push(`      name: '${ALL_NAME}'`)
for (const p of plugins) {
  out.push('')
  out.push(`# from ../${p.dir}`)
  out.push('- insert:')
  for (const row of p.rows) {
    out.push(`    - id: ${row.id}`)
    out.push(`      name: '${row.name}'`)
  }
}
writeFileSync(join(packagesDir, 'all', 'cordis.patch.yml'), out.join('\n') + '\n')

// 2) 同步 packages/all/package.json 的 dependencies（插件 → 精确版本）
//
// 不能用 workspace:*：pnpm publish 会把它替换成真实版本（所以 npm 产物是对的），
// 但从 git 子路径安装（git+https://...#main&path:packages/all）时协议原样保留，
// 消费者侧 pnpm 找不到同名 workspace 包直接 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND。
// 同理根 bundle 也要真实版本——它在 profile / 市场安装里独立解析。
//
// 版本取各插件自己的 package.json：发布流是「先 bump 本地版本 → aggregate → 发布」，
// 本地版本即本次要发布的版本（未 bump 的包其版本已存在于 registry），两者恒等。
const allPkgPath = join(packagesDir, 'all', 'package.json')
const allPkg = readJson(allPkgPath)
// 上一轮提交态（用于提示本次有哪些包被 bump），值可能是历史遗留的 workspace:*
const previousVersions = { ...(allPkg.dependencies ?? {}) }
const deps = { ...(allPkg.dependencies ?? {}) }
for (const key of Object.keys(deps)) {
  if (key.startsWith('@hyzyn/dsh-')) delete deps[key]
}
const pluginVersions = {}
for (const p of plugins) {
  pluginVersions[p.name] = p.version
  deps[p.name] = p.version
}
allPkg.dependencies = Object.fromEntries(Object.entries(deps).sort())
writeFileSync(allPkgPath, JSON.stringify(allPkg, null, 2) + '\n')

console.log(`[aggregate] ${plugins.length} 个插件 → packages/all/cordis.patch.yml + dependencies`)
for (const p of plugins) {
  const prev = previousVersions[p.name]
  const bumped = prev && prev !== p.version ? `  ${prev} → ${p.version}` : ''
  console.log(`  - ${p.name}@${p.version}${bumped}  (rows: ${p.rows.map((r) => r.id).join(', ')})`)
}

// 3) 生成仓库根 bundle：根 cordis.patch.yml + 根 package.json dependencies。
//    根包声明 dsh.bundle.patch 后，DSH 加载器（dsh.bundle 判定）与 DSH 插件市场
//    （looksLikeDshPlugin：dsh 字段 / @deepseek-ai/* 依赖）都会把仓库根识别为
//    DSH 插件；`dsh plugin --profile web add link:$(pwd)` 一条命令挂载全家桶。
//    依赖取各插件本次的发布版本（见 pluginVersions），与 packages/all 保持一致；
//    不能用 workspace:*——npm 不支持该协议，且 git 子路径安装时原样保留会解析失败，
//    根包要在 profile / 市场安装里独立解析。
const rootPkgPath = join(root, 'package.json')
const rootPkg = readJson(rootPkgPath)
const rootOut = ['# AUTO-GENERATED by scripts/aggregate.mjs — do not edit', '# 重新生成：pnpm aggregate', '']
rootOut.push('# from self')
rootOut.push('- insert:')
rootOut.push('    - id: dsh-plugin-kit')
rootOut.push(`      name: '${rootPkg.name}'`)
for (const p of plugins) {
  rootOut.push('')
  rootOut.push(`# from ../packages/${p.dir}`)
  rootOut.push('- insert:')
  for (const row of p.rows) {
    rootOut.push(`    - id: ${row.id}`)
    rootOut.push(`      name: '${row.name}'`)
  }
}
writeFileSync(join(root, 'cordis.patch.yml'), rootOut.join('\n') + '\n')

const rootDeps = { ...(rootPkg.dependencies ?? {}) }
for (const key of Object.keys(rootDeps)) {
  if (key.startsWith('@hyzyn/dsh-')) delete rootDeps[key]
}
for (const p of plugins) {
  rootDeps[p.name] = pluginVersions[p.name]
}
rootPkg.dependencies = Object.fromEntries(Object.entries(rootDeps).sort())
writeFileSync(rootPkgPath, JSON.stringify(rootPkg, null, 2) + '\n')

console.log(`[aggregate] ${plugins.length} 个插件 → 根 cordis.patch.yml + dependencies（dsh-plugin-kit bundle）`)
