#!/usr/bin/env node
/**
 * 生成 @hyzyn/dsh-all 聚合清单：
 *   packages/all/cordis.patch.yml —— 自身行 + 全部插件行
 *   packages/all/package.json dependencies —— 全部插件 workspace:*
 * 扫描规则：packages 下各子目录的 package.json 含 dsh.bundle.patch、且包名不是 @hyzyn/dsh-all。
 * 每行的 id 与包名从插件自己的 cordis.patch.yml 提取。
 * 用法：pnpm aggregate（仓库根目录）
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const packagesDir = join(root, 'packages')
const ALL_NAME = '@hyzyn/dsh-all'

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'))
}

/** 从插件自己的 cordis.patch.yml 提取 insert 行（id + 包名）。 */
function extractRows(yaml) {
  const rows = []
  const lines = yaml.split(/\r?\n/)
  for (let i = 0; i < lines.length; i++) {
    const idMatch = /^\s*-\s+id:\s*(\S+)\s*$/.exec(lines[i])
    if (!idMatch) continue
    let pkg = null
    for (let j = i + 1; j < Math.min(lines.length, i + 4); j++) {
      const nameMatch = /^\s*name:\s*'([^']+)'\s*$/.exec(lines[j])
      if (nameMatch) {
        pkg = nameMatch[1]
        break
      }
    }
    if (pkg) rows.push({ id: idMatch[1], name: pkg })
  }
  return rows
}

const plugins = []
for (const dir of readdirSync(packagesDir).sort()) {
  if (!/^[a-z0-9-]+$/.test(dir)) continue
  const pkgPath = join(packagesDir, dir, 'package.json')
  let pkg
  try {
    pkg = readJson(pkgPath)
  } catch {
    continue
  }
  if (pkg.name === ALL_NAME) continue
  const patchRel = pkg.dsh?.bundle?.patch
  if (!patchRel) continue
  let rows
  try {
    rows = extractRows(readFileSync(join(packagesDir, dir, patchRel), 'utf8'))
  } catch {
    continue
  }
  if (rows.length === 0) {
    console.warn(`[aggregate] 跳过 ${pkg.name}：cordis.patch.yml 中没有可提取的行`)
    continue
  }
  plugins.push({ dir, name: pkg.name, rows })
}

// 1) 重写 packages/all/cordis.patch.yml
const out = ['# AUTO-GENERATED by scripts/aggregate.mjs — do not edit', '# 重新生成：pnpm aggregate', '']
out.push('# from self')
out.push('- insert:')
out.push('    - id: all')
out.push(`      name: '${ALL_NAME}'`)
for (const p of plugins) {
  out.push('')
  out.push(`# from ../${p.dir}`)
  out.push('- insert:')
  for (const row of p.rows) {
    out.push(`    - id: ${row.id}`)
    out.push(`      name: '${row.name}'`)
  }
}
writeFileSync(join(packagesDir, 'all', 'cordis.patch.yml'), out.join('\n') + '\n')

// 2) 同步 packages/all/package.json 的 dependencies（插件 → workspace:*）
const allPkgPath = join(packagesDir, 'all', 'package.json')
const allPkg = readJson(allPkgPath)
const deps = { ...(allPkg.dependencies ?? {}) }
for (const key of Object.keys(deps)) {
  if (key.startsWith('@hyzyn/dsh-')) delete deps[key]
}
for (const p of plugins) deps[p.name] = 'workspace:*'
allPkg.dependencies = Object.fromEntries(Object.entries(deps).sort())
writeFileSync(allPkgPath, JSON.stringify(allPkg, null, 2) + '\n')

console.log(`[aggregate] ${plugins.length} 个插件 → packages/all/cordis.patch.yml + dependencies`)
for (const p of plugins) {
  console.log(`  - ${p.name}  (rows: ${p.rows.map((r) => r.id).join(', ')})`)
}
